version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
    ports:
      - "5252:5252"
    container_name: softy-pinko-back-end

  front-end:
    build:
      context: ./front-end
    ports:
      - "9000:9000"
    container_name: softy-pinko-front-end
    depends_on:
      - back-end
