version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
    expose:
      - "5252"
    container_name: softy-pinko-back-end-1

  back-end-2:
    build:
      context: ./back-end
    expose:
      - "5252"
    container_name: softy-pinko-back-end-2

  front-end:
    build:
      context: ./front-end
    expose:
      - "9000"
    container_name: softy-pinko-front-end
    depends_on:
      - back-end
      - back-end-2

  proxy:
    build:
      context: ./proxy
    image: nginx-proxy
    ports:
      - "80:80"
    container_name: softy-pinko-proxy
    depends_on:
      - front-end
      - back-end
      - back-end-2

